"""Artistic styles — generated verbatim from bot.py ESTILOS_ARTISTICOS.

Do NOT hand-edit. Run scripts/extract_bot_dicts.py to regenerate.
"""

CATEGORIES = { 'anime': 'Anime & Manga',
  'cartoon': 'Cartoon & Disney',
  'comic': 'Comic & Ilustração',
  'fantasy': 'Fantasy & Sci-Fi',
  'paint': 'Pintura Tradicional',
  'vintage': 'Vintage & Retro',
  'other': 'Outros'}

ARTISTIC_STYLES = [ { 'id': 'anime',
    'label': 'Anime',
    'cat': 'anime',
    'suffix': 'transform into anime style, anime art, manga aesthetic, keep same pose'},
  { 'id': 'ghibli',
    'label': 'Ghibli',
    'cat': 'anime',
    'suffix': 'transform into Studio Ghibli anime style, soft colors, Miyazaki aesthetic'},
  { 'id': 'disney_2d',
    'label': 'Disney 2D',
    'cat': 'cartoon',
    'suffix': 'transform into Disney 2D animation style character'},
  { 'id': 'disney_3d',
    'label': 'Disney 3D',
    'cat': 'cartoon',
    'suffix': 'transform into Disney Pixar 3D character style, cute 3D render'},
  { 'id': 'cartoon',
    'label': 'Cartoon',
    'cat': 'cartoon',
    'suffix': 'transform into cartoon style, colorful, exaggerated features, fun cartoon'},
  { 'id': 'comic',
    'label': 'Comic',
    'cat': 'comic',
    'suffix': 'transform into comic book style, bold lines, vibrant colors'},
  { 'id': 'manga',
    'label': 'Manga',
    'cat': 'anime',
    'suffix': 'transform into black and white manga style, detailed ink drawing, manga panels'},
  { 'id': 'pokemon_2d',
    'label': 'Pokemon 2D',
    'cat': 'cartoon',
    'suffix': 'transform into Pokemon 2D art style, Nintendo Pokemon game aesthetic'},
  { 'id': 'pokemon_3d',
    'label': 'Pokemon 3D',
    'cat': 'cartoon',
    'suffix': 'transform into Pokemon 3D render style, Nintendo 3D Pokemon'},
  { 'id': 'cyberpunk',
    'label': 'Cyberpunk',
    'cat': 'fantasy',
    'suffix': 'transform into cyberpunk style, neon lights, futuristic, dark atmosphere'},
  { 'id': 'retrowave',
    'label': 'Retrowave',
    'cat': 'fantasy',
    'suffix': 'transform into retrowave synthwave style, neon pink purple, 80s aesthetic'},
  { 'id': 'fantasy',
    'label': 'Fantasy',
    'cat': 'fantasy',
    'suffix': 'transform into epic fantasy painting, magical atmosphere, fantasy art'},
  { 'id': 'pixel_art',
    'label': 'Pixel Art',
    'cat': 'other',
    'suffix': 'transform into pixel art style, retro game aesthetic, 16-bit style'},
  { 'id': 'watercolor',
    'label': 'Watercolor',
    'cat': 'paint',
    'suffix': 'transform into watercolor painting, soft colors, artistic watercolor'},
  { 'id': 'oil_paint',
    'label': 'Oil Paint',
    'cat': 'paint',
    'suffix': 'transform into oil painting, classical art style, rich textures'},
  { 'id': 'digital_art',
    'label': 'Digital Art',
    'cat': 'paint',
    'suffix': 'transform into digital painting, detailed digital art, artstation quality'},
  { 'id': 'concept_art',
    'label': 'Concept Art',
    'cat': 'paint',
    'suffix': 'transform into concept art, professional concept sketch, game art style'},
  { 'id': 'sketch',
    'label': 'Sketch',
    'cat': 'paint',
    'suffix': 'transform into pencil drawing sketch, black and white, detailed lines'},
  { 'id': 'cute_3d',
    'label': 'Cute 3D',
    'cat': 'cartoon',
    'suffix': 'transform into cute 3D chibi character, kawaii 3D render, adorable'},
  { 'id': 'claymation',
    'label': 'Claymation',
    'cat': 'cartoon',
    'suffix': 'transform into claymation stop motion style, clay figures, handmade look'},
  { 'id': 'ukiyoe',
    'label': 'Ukiyo-e',
    'cat': 'paint',
    'suffix': 'transform into Japanese ukiyo-e woodblock print style, traditional art'},
  { 'id': 'art_nouveau',
    'label': 'Art Nouveau',
    'cat': 'paint',
    'suffix': 'transform into Art Nouveau style, ornate decorative, flowing lines'},
  { 'id': 'tattoo',
    'label': 'Tattoo',
    'cat': 'other',
    'suffix': 'transform into tattoo design style, ink art, bold outlines, tattoo flash'},
  { 'id': 'vintage',
    'label': 'Vintage',
    'cat': 'vintage',
    'suffix': 'transform into vintage retro style, aged colors, nostalgic aesthetic'},
  { 'id': 'splatter',
    'label': 'Splatter',
    'cat': 'paint',
    'suffix': 'transform into paint splatter art, abstract colorful splashes, explosive'},
  { 'id': 'grain',
    'label': 'Film Grain',
    'cat': 'vintage',
    'suffix': 'transform with film grain effect, analog photography, cinematic grain'},
  { 'id': 'woodcarving',
    'label': 'Woodcarving',
    'cat': 'other',
    'suffix': 'transform into woodcarving art style, carved wood texture, relief sculpture'},
  { 'id': 'furry',
    'label': 'Furry',
    'cat': 'other',
    'suffix': 'transform into furry art style, anthropomorphic animal character, detailed fur'},
  { 'id': 'pop_art',
    'label': 'Pop Art',
    'cat': 'comic',
    'suffix': 'transform into pop art style, Andy Warhol inspired, bold colors, halftone dots'},
  { 'id': 'steampunk',
    'label': 'Steampunk',
    'cat': 'fantasy',
    'suffix': 'transform into steampunk style, Victorian mechanical, gears and brass'},
  { 'id': 'anime_50s',
    'label': 'Anime 50s',
    'cat': 'anime',
    'suffix': 'transform into 1950s anime infomercial style, retro anime housewife aesthetic, vintage anime'},
  { 'id': 'neon_glow',
    'label': 'Neon Glow',
    'cat': 'fantasy',
    'suffix': 'transform with neon glow effect, glowing edges, dark background, vibrant neon colors'},
  { 'id': 'gothic',
    'label': 'Gothic',
    'cat': 'fantasy',
    'suffix': 'transform into gothic dark art style, dark aesthetic, moody atmosphere, dark fantasy'}]


def get_artistic(style_id: str):
    for s in ARTISTIC_STYLES:
        if s["id"] == style_id:
            return s
    return None
