"""44 Poster templates organized in 5 categories.
Each template has placeholders (e.g. {title}, {date}, {venue}) that the user fills.
Generated via OpenAI gpt-image-1 (15 credits).
"""

POSTER_TEMPLATES = [
    # ===== MUSIC (10) =====
    {"id": "music_concert", "category": "music", "label": "Concert Tour Poster",
     "placeholders": ["artist_name", "tour_name", "dates", "venue"],
     "prompt": "Cinematic concert tour poster for {artist_name}. Tour name {tour_name} prominently typeset. Tour dates {dates}. Venue {venue}. Dramatic stage lighting, bold serif type, editorial layout. Vertical 4:5."},
    {"id": "music_album", "category": "music", "label": "Album Cover",
     "placeholders": ["album_name", "artist_name"],
     "prompt": "Editorial album cover. Album '{album_name}' by {artist_name}. Bold modernist typography, evocative mood, museum poster aesthetic. Square 1:1."},
    {"id": "music_festival", "category": "music", "label": "Festival Lineup",
     "placeholders": ["festival_name", "headliners", "dates"],
     "prompt": "Music festival poster for {festival_name}. Headliners: {headliners}. Dates {dates}. Iconic festival typography hierarchy, sun-warmed gradient, retro-modern. Vertical 4:5."},
    {"id": "music_dj", "category": "music", "label": "DJ Night",
     "placeholders": ["dj_name", "club", "date"],
     "prompt": "Electronic club night flyer. DJ {dj_name}. Venue {club}. Date {date}. Brutalist typography, neon accents on dark, high-contrast. Vertical 9:16."},
    {"id": "music_jazz", "category": "music", "label": "Jazz Evening",
     "placeholders": ["title", "performer", "venue", "date"],
     "prompt": "Vintage jazz evening poster. Title {title}, performer {performer}. {venue}, {date}. 1950s typographic style, warm sepia, classic elegance. Vertical 4:5."},
    {"id": "music_classical", "category": "music", "label": "Symphony Night",
     "placeholders": ["orchestra", "piece", "conductor", "date"],
     "prompt": "Symphony night poster. {orchestra} performs {piece}, conducted by {conductor}, on {date}. Marble texture, refined serif, classical luxury. Vertical 4:5."},
    {"id": "music_indie", "category": "music", "label": "Indie Show",
     "placeholders": ["band", "venue", "date"],
     "prompt": "Indie band show poster for {band} at {venue}, {date}. Risograph-style printing, two-color, lo-fi charm, hand-drawn type. Vertical 4:5."},
    {"id": "music_hiphop", "category": "music", "label": "Hip-hop Drop",
     "placeholders": ["artist", "release_title", "date"],
     "prompt": "Hip-hop release poster. Artist {artist}, release {release_title}, drop date {date}. Y2K aesthetic, chrome typography, urban texture. Vertical 4:5."},
    {"id": "music_acoustic", "category": "music", "label": "Acoustic Set",
     "placeholders": ["performer", "venue", "date"],
     "prompt": "Acoustic evening poster. {performer} at {venue}, {date}. Warm candle-lit photograph, handwritten title, intimate vibe. Vertical 4:5."},
    {"id": "music_release", "category": "music", "label": "Single Release",
     "placeholders": ["single", "artist", "release_date"],
     "prompt": "New single release poster. '{single}' by {artist}, out {release_date}. Bold contemporary type, abstract gradient background. Square 1:1."},

    # ===== EVENTS (10) =====
    {"id": "event_wedding", "category": "events", "label": "Wedding Invite",
     "placeholders": ["couple_names", "date", "venue"],
     "prompt": "Editorial wedding invitation. {couple_names}, on {date}, at {venue}. Elegant serif type, botanical illustration, warm cream palette. Vertical 4:5."},
    {"id": "event_birthday", "category": "events", "label": "Birthday Party",
     "placeholders": ["name", "age", "date", "venue"],
     "prompt": "Birthday party poster. {name} turns {age}. {date} at {venue}. Festive playful typography, confetti texture, warm celebratory mood. Vertical 4:5."},
    {"id": "event_corporate", "category": "events", "label": "Corporate Event",
     "placeholders": ["company", "event_name", "date", "venue"],
     "prompt": "Minimal corporate event poster. {company} presents {event_name} on {date}, {venue}. Premium typography grid, monochrome with single accent. Vertical 4:5."},
    {"id": "event_workshop", "category": "events", "label": "Workshop",
     "placeholders": ["workshop_title", "instructor", "date"],
     "prompt": "Workshop announcement. {workshop_title}, hosted by {instructor}, on {date}. Editorial magazine layout, clean serif/sans pairing. Vertical 4:5."},
    {"id": "event_art_show", "category": "events", "label": "Art Exhibition",
     "placeholders": ["artist", "exhibition_title", "dates", "gallery"],
     "prompt": "Gallery exhibition poster. Artist {artist}. {exhibition_title}. {dates} at {gallery}. Museum poster aesthetic, refined typography. Vertical 4:5."},
    {"id": "event_film_screening", "category": "events", "label": "Film Screening",
     "placeholders": ["film", "date", "venue"],
     "prompt": "Film screening poster. {film}. Screening {date} at {venue}. Cinematic still frame, classic film title treatment. Vertical 4:5."},
    {"id": "event_charity", "category": "events", "label": "Charity Gala",
     "placeholders": ["organization", "event_name", "date"],
     "prompt": "Charity gala poster. {organization} presents {event_name}, {date}. Elegant black-tie aesthetic, gold accents on deep purple, formal typography. Vertical 4:5."},
    {"id": "event_conference", "category": "events", "label": "Conference",
     "placeholders": ["conference_name", "speakers", "dates"],
     "prompt": "Tech conference poster. {conference_name}. Featuring {speakers}. {dates}. Modern geometric design, premium typography. Vertical 4:5."},
    {"id": "event_meetup", "category": "events", "label": "Community Meetup",
     "placeholders": ["topic", "date", "location"],
     "prompt": "Community meetup announcement. Topic: {topic}. {date} at {location}. Friendly approachable typography, warm color palette. Vertical 4:5."},
    {"id": "event_grand_opening", "category": "events", "label": "Grand Opening",
     "placeholders": ["business_name", "date", "address"],
     "prompt": "Grand opening announcement for {business_name}. Opening {date} at {address}. Celebratory but classy, ribbon-cut imagery, elegant typography. Vertical 4:5."},

    # ===== BEFORE/AFTER (8) =====
    {"id": "ba_renovation", "category": "before_after", "label": "Home Renovation",
     "placeholders": ["title", "tag_before", "tag_after"],
     "prompt": "Editorial before/after split layout. Title {title}. Left labeled {tag_before}, right labeled {tag_after}. Magazine-quality typography. Wide 16:9."},
    {"id": "ba_fitness", "category": "before_after", "label": "Fitness Journey",
     "placeholders": ["title", "duration"],
     "prompt": "Fitness transformation poster. Title {title}. Duration {duration}. Side-by-side composition, bold motivational typography. Vertical 9:16."},
    {"id": "ba_makeup", "category": "before_after", "label": "Makeup Look",
     "placeholders": ["title", "stylist"],
     "prompt": "Beauty before/after poster. {title}. Stylist credit: {stylist}. Editorial magazine, soft beauty light. Square 1:1."},
    {"id": "ba_hair", "category": "before_after", "label": "Hair Restyle",
     "placeholders": ["title", "salon"],
     "prompt": "Hair restyle showcase, before/after split. {title}. Salon {salon}. Glossy fashion typography, refined neutrals. Square 1:1."},
    {"id": "ba_car", "category": "before_after", "label": "Car Restoration",
     "placeholders": ["model", "year"],
     "prompt": "Car restoration poster. Vehicle {model}, year {year}. Before/after split, garage backdrop, bold racing-style typography. Wide 16:9."},
    {"id": "ba_garden", "category": "before_after", "label": "Garden Makeover",
     "placeholders": ["title"],
     "prompt": "Garden makeover before/after. Title {title}. Natural botanical typography, soft daylight. Wide 16:9."},
    {"id": "ba_room", "category": "before_after", "label": "Room Reveal",
     "placeholders": ["room", "designer"],
     "prompt": "Interior room reveal. {room} designed by {designer}. Architectural Digest style typography, refined palette. Wide 16:9."},
    {"id": "ba_food", "category": "before_after", "label": "Recipe Transformation",
     "placeholders": ["dish", "chef"],
     "prompt": "Food before/after — raw ingredients vs. finished {dish}. By {chef}. Editorial food-magazine typography. Square 1:1."},

    # ===== EDITORIAL (8) =====
    {"id": "ed_magazine_cover", "category": "editorial", "label": "Magazine Cover",
     "placeholders": ["magazine_name", "issue", "headline"],
     "prompt": "Magazine cover design. Title {magazine_name}, issue {issue}. Headline: {headline}. Bold masthead, full-bleed portrait, professional grid. Vertical 4:5."},
    {"id": "ed_feature", "category": "editorial", "label": "Feature Page",
     "placeholders": ["headline", "deck"],
     "prompt": "Magazine feature opening spread. Headline {headline}. Deck: {deck}. Refined serif typography, generous whitespace. Wide 16:9."},
    {"id": "ed_quote_card", "category": "editorial", "label": "Quote Card",
     "placeholders": ["quote", "author"],
     "prompt": "Editorial quote card. Pull quote: '{quote}'. Attributed to {author}. Italic serif type, soft minimalist background. Square 1:1."},
    {"id": "ed_news", "category": "editorial", "label": "News Banner",
     "placeholders": ["headline", "publication"],
     "prompt": "News banner. Headline {headline}. Publication {publication}. Authoritative serif headline, refined photo treatment. Wide 16:9."},
    {"id": "ed_film_review", "category": "editorial", "label": "Film Review",
     "placeholders": ["film", "rating"],
     "prompt": "Film review editorial layout. Film {film}. Rating {rating}/5. Classic critic typography, soft poster collage. Vertical 4:5."},
    {"id": "ed_book", "category": "editorial", "label": "Book Cover",
     "placeholders": ["book_title", "author"],
     "prompt": "Editorial book cover. Title {book_title} by {author}. Modernist publishing house aesthetic, hand-set type. Vertical 4:5."},
    {"id": "ed_essay", "category": "editorial", "label": "Essay Title",
     "placeholders": ["title", "subhead"],
     "prompt": "Essay title page. Title {title}. Subhead {subhead}. Refined serif, expansive whitespace, philosophical mood. Vertical 4:5."},
    {"id": "ed_obituary", "category": "editorial", "label": "Tribute Card",
     "placeholders": ["name", "years"],
     "prompt": "Tribute card. {name} ({years}). Sober monochrome design, classical serif, dignified typography. Square 1:1."},

    # ===== PROMO (8) =====
    {"id": "promo_sale", "category": "promo", "label": "Sale Announcement",
     "placeholders": ["brand", "discount", "deadline"],
     "prompt": "Retail sale poster. {brand}, {discount} off, until {deadline}. Bold modern typography, on-brand color blocks. Vertical 9:16."},
    {"id": "promo_launch", "category": "promo", "label": "Product Launch",
     "placeholders": ["product", "tagline", "launch_date"],
     "prompt": "Product launch poster. {product}. Tagline: {tagline}. Launch {launch_date}. Premium typography, hero product visual. Vertical 4:5."},
    {"id": "promo_app", "category": "promo", "label": "App Promo",
     "placeholders": ["app_name", "tagline"],
     "prompt": "App promo poster. {app_name}. Tagline {tagline}. Sleek tech-startup aesthetic, generous whitespace, gradient accent. Vertical 9:16."},
    {"id": "promo_food", "category": "promo", "label": "Food Special",
     "placeholders": ["restaurant", "dish", "price"],
     "prompt": "Restaurant special poster. {restaurant} presents {dish} at {price}. Editorial food photography typography. Vertical 4:5."},
    {"id": "promo_fashion", "category": "promo", "label": "Fashion Drop",
     "placeholders": ["brand", "collection", "season"],
     "prompt": "Fashion drop announcement. Brand {brand}. Collection {collection}, season {season}. Editorial magazine campaign aesthetic. Vertical 4:5."},
    {"id": "promo_real_estate", "category": "promo", "label": "Property Listing",
     "placeholders": ["address", "price", "agent"],
     "prompt": "Luxury real estate listing. Property {address}, price {price}. Agent {agent}. Architectural editorial style, refined typography. Vertical 4:5."},
    {"id": "promo_service", "category": "promo", "label": "Service Promo",
     "placeholders": ["service", "company", "offer"],
     "prompt": "Service promotion. {service} by {company}. Offer: {offer}. Trustworthy professional typography, single accent color. Vertical 4:5."},
    {"id": "promo_event_ticket", "category": "promo", "label": "Event Ticket",
     "placeholders": ["event", "date", "seat"],
     "prompt": "Stylized event ticket design. {event}, {date}, seat {seat}. Vintage ticket aesthetic, refined typography. Wide 16:9."},

    # ===== SOCIAL MEDIA (6) =====
    {"id": "sm_story", "category": "social_media", "label": "Instagram Story",
     "placeholders": ["headline", "subtext", "cta"],
     "prompt": "Instagram story design. Headline {headline}. Subtext {subtext}. Call to action: {cta}. Bold modern typography, vibrant gradient background, mobile-first vertical layout. Vertical 9:16."},
    {"id": "sm_feed", "category": "social_media", "label": "Feed Post",
     "placeholders": ["headline", "caption", "brand"],
     "prompt": "Instagram feed post. Headline {headline}. Caption {caption}. Brand {brand}. Premium editorial layout, clean typography, scroll-stopping visual. Square 1:1."},
    {"id": "sm_quote", "category": "social_media", "label": "Quote Post",
     "placeholders": ["quote", "author", "brand"],
     "prompt": "Social media quote post. Pull quote: '{quote}'. Attributed to {author}. Brand {brand}. Elegant serif typography on soft gradient. Square 1:1."},
    {"id": "sm_announcement", "category": "social_media", "label": "Announcement",
     "placeholders": ["headline", "date", "details"],
     "prompt": "Social announcement post. Headline {headline}. Date {date}. Details {details}. Bold attention-grabbing typography, celebratory mood. Square 1:1."},
    {"id": "sm_reel_cover", "category": "social_media", "label": "Reel Cover",
     "placeholders": ["title", "hook", "episode"],
     "prompt": "Reel/TikTok cover thumbnail. Title {title}. Hook {hook}. Episode {episode}. Eye-catching typography, vivid colors, designed to stop the scroll. Vertical 9:16."},
    {"id": "sm_carousel_cover", "category": "social_media", "label": "Carousel Cover",
     "placeholders": ["title", "subtitle", "swipe_text"],
     "prompt": "Instagram carousel cover slide. Title {title}. Subtitle {subtitle}. Swipe text {swipe_text}. Editorial premium design with clear visual hierarchy. Square 1:1."},
]


def get_poster(template_id: str):
    for p in POSTER_TEMPLATES:
        if p["id"] == template_id:
            return p
    return None
