/**
 * Hidden cinematic ad prompt library — 15s, shot-by-shot, Seedance-safe (<3900 chars).
 * Placeholders: __PRODUCT__ __REFS__
 */

function ad(intro, shots, audio, style) {
  const body = shots
    .map((s, i) => {
      const times = [
        "0:00-0:02", "0:02-0:03", "0:03-0:04", "0:04-0:05", "0:05-0:07",
        "0:07-0:08", "0:08-0:09", "0:09-0:11", "0:11-0:12", "0:12-0:15",
      ];
      return `Shot ${i + 1} (${times[i]}): ${s}`;
    })
    .join("\n\n");
  return (
    `${intro} __REFS__\n\n`
    + `${body}\n\n`
    + `Audio: ${audio}\n\n`
    + `Style: ${style} No text overlays or watermarks unless on reference packaging.`
  );
}

const BASE = "Create an intense cinematic marketing advertisement for __PRODUCT__.";
const AUDIO_PREMIUM =
  "High-energy premium commercial soundtrack! Dynamic bass hits, cinematic risers, impactful transitions, and sound effects synced to every cut!";
const STYLE_BASE =
  "Ultra-realistic luxury commercial production, dramatic lighting, hyper-detailed textures, professional advertising cinematography, dynamic camera movement!";

function entry(id, storyboard, intro, shots, audio, styleExtra = "") {
  return {
    id,
    storyboard,
    weight: 1,
    generateAudio: true,
    prompt: ad(intro, shots, audio, `${STYLE_BASE} ${styleExtra}`.trim()),
  };
}

const FASHION = [
  entry("fashion_runway_15", "Runway reveal — editorial fashion film",
    `${BASE} Match lighting and atmosphere to garment colors and brand identity.`,
    [
      "Dark void explodes into runway spotlight! Fabric silhouette emerges through volumetric haze. Wide low-angle, aggressive energy build-up! Whip pan into Shot 2.",
      "Model stride in slow motion — garment flows with wind and light trails matching brand palette! Handheld speed ramp. Smash cut to Shot 3.",
      "Extreme macro on fabric weave and stitching! Thread texture, dye depth, premium material detail. Shallow DOF, 25% slow motion. Tilt into Shot 4.",
      "Ultra-macro on label, button, or logo detail through soft focus! Rim light on texture. Push-in accelerates into Shot 5.",
      "Full outfit hero reveal on stylized set inspired by brand colors! Crane rise emphasizing silhouette and confidence! Into Shot 6.",
      "Bird's-eye view — outfit centered on geometric floor pattern in brand tones! Slow orbit begins into Shot 7.",
      "Eye-level orbit — floating fabric particles, light flares, editorial energy! Steadicam slow-mo ramp into Shot 8.",
      "Close-up styling detail — hand adjusts collar, sleeve, or accessory! Macro shallow focus into Shot 9.",
      "Final walk toward camera in slow motion — confidence, power, fashion authority! Tracking backward into Shot 10.",
      "Hero freeze — model and product dominate frame! Volumetric light, telephoto compression, maximum advertising impact!",
    ], AUDIO_PREMIUM, "High-fashion editorial energy, Vogue-level production!"),

  entry("fashion_street_15", "Street style — urban fashion energy",
    `${BASE} Urban environment inspired by streetwear culture and product colors.`,
    [
      "Rain-slick city alley at night! Neon reflections in puddles build energy. Low-angle wide, handheld grit! Whip pan to Shot 2.",
      "Product bursts into frame on concrete with graffiti bokeh! Particles and city dust fly toward camera! Speed ramp into Shot 3.",
      "Macro on sneaker stitching, denim texture, or streetwear detail! Urban grit meets premium craft. Slow tilt to Shot 4.",
      "Brand tag or logo macro with neon rim light! Push-in into Shot 5.",
      "Hero outfit on rooftop at golden hour — city skyline backdrop! Dynamic wind and attitude! Crane into Shot 6.",
      "Top-down street-style composition! Bold colors radiate outward! Orbit into Shot 7.",
      "Eye-level tracking walk through urban crowd blur! Product stays sharp — cinematic isolation! Into Shot 8.",
      "Hands adjust cap, hoodie, or jacket — authentic street moment! Macro into Shot 9.",
      "Slow-motion jump or spin showcasing full look! High energy! Into Shot 10.",
      "Final hero — subject owns the frame against city lights! Hold for impact!",
    ], AUDIO_PREMIUM, "Urban streetwear commercial, gritty yet premium!"),

  entry("fashion_fabric_15", "Fabric & texture — tactile luxury",
    `${BASE} Emphasize material quality, drape, and tactile premium feel.`,
    [
      "Black studio void! Single beam reveals fabric edge catching light! Slow push-in! Into Shot 2.",
      "Fabric unfolds in slow motion — silk, wool, or cotton ripples with brand-colored light! Particles float! Smash cut to Shot 3.",
      "Extreme macro fiber texture — every thread visible! Moisture-like sheen on premium material! 25% slow-mo into Shot 4.",
      "Macro on embroidery, print, or pattern detail! Color accuracy from references! Push-in to Shot 5.",
      "Garment on invisible form — dramatic drape and movement! Wind machine elegance! Crane into Shot 6.",
      "Overhead flat-lay spin — accessories arranged in brand palette! Clockwise orbit into Shot 7.",
      "Side-lit silhouette showing cut and fit! Floating lint and light motes! Steadicam into Shot 8.",
      "Hands smooth fabric — tactile ASMR-quality detail! Macro into Shot 9.",
      "Color gradient wash transitions through garment hues! Fluid motion! Into Shot 10.",
      "Final hero — product fills frame in pure luxury light! Hold!",
    ], `${AUDIO_PREMIUM} Soft fabric rustle SFX layered in.`, "Tactile fabric luxury, ASMR-quality texture!"),

  entry("fashion_editorial_15", "Editorial flash — high-contrast fashion",
    `${BASE} High-contrast editorial lighting matching brand identity.`,
    [
      "Pitch black! Strobe flashes reveal frozen fashion poses! Aggressive rhythm! Whip pan to Shot 2.",
      "Continuous strobe sequence — product details flash in and out! Energy builds! Into Shot 3.",
      "Macro lens on accessory, buckle, or jewelry on garment! Flash freeze frames! Slow-mo into Shot 4.",
      "Close on eyes, lips, or styling above product — editorial mystery! Push-in to Shot 5.",
      "Full look revealed in single powerful flash! Smoke and colored gels! Crane into Shot 6.",
      "Overhead geometric light pattern on model! Orbit into Shot 7.",
      "Silhouette walk with rim light only — premium mystery! Steadicam into Shot 8.",
      "Detail shot — zipper, clasp, or heel! Macro sparkle! Into Shot 9.",
      "Slow spin with fabric fan effect! Maximum drama! Into Shot 10.",
      "Final flash freeze hero — iconic advertising frame! Hold!",
    ], `${AUDIO_PREMIUM} Strobe-synced beat hits!`, "Editorial flash photography, high-contrast fashion film!"),

  entry("fashion_boutique_15", "Boutique luxury — warm retail elegance",
    `${BASE} Warm boutique atmosphere inspired by luxury retail.`,
    [
      "Elegant boutique interior blur! Warm tungsten glow! Product enters on velvet pedestal! Push-in to Shot 2.",
      "Soft spotlight on garment — mannequin or model silhouette! Dust motes in warm light! Into Shot 3.",
      "Macro on premium label, leather, or cashmere! Shallow DOF luxury! Tilt to Shot 4.",
      "Close on shopping bag texture or gift ribbon in brand colors! Push-in to Shot 5.",
      "Model twirls in boutique mirror reflection — dual frame composition! Crane into Shot 6.",
      "Overhead boutique layout — product centered among styled props! Orbit into Shot 7.",
      "Eye-level mirror reveal — product from front and reflection! Steadicam into Shot 8.",
      "Hands touch fabric on rack — selective focus! Macro into Shot 9.",
      "Slow walk past window display — golden hour light! Into Shot 10.",
      "Final hero on pedestal — boutique luxury perfection! Hold!",
    ], `${AUDIO_PREMIUM} Soft boutique ambience with elegant transitions!`, "Warm luxury boutique commercial!"),

  entry("fashion_athletic_15", "Athletic power — sportswear energy",
    `${BASE} High-performance athletic energy matching sportswear branding.`,
    [
      "Dark gym void! Explosive light burst! Product slams into frame with impact dust! Low-angle power! Whip to Shot 2.",
      "Athlete silhouette mid-motion — sweat particles frozen! Speed ramp! Smash cut to Shot 3.",
      "Macro on breathable mesh, sole grip, or performance fabric! Technical detail hero! Into Shot 4.",
      "Brand logo on gear — macro with sweat droplet reflection! Push-in to Shot 5.",
      "Full action hero — jump, sprint, or lift in branded environment! Dynamic low-angle! Crane into Shot 6.",
      "Top-down gear layout — shoes, apparel, accessories! Energy pulse waves! Orbit into Shot 7.",
      "Tracking alongside motion — product stays razor sharp! Steadicam into Shot 8.",
      "Lacing shoes or pulling on gear — hands macro! Into Shot 9.",
      "Victory slow-motion finish — power and achievement! Into Shot 10.",
      "Final hero — athletic product dominates! Maximum impact hold!",
    ], `${AUDIO_PREMIUM} Punchy sports commercial beats and impact SFX!`, "Nike-level athletic commercial energy!"),
];

const DRINKS = [
  entry("drinks_energy_15", "Energy drink — cinematic power (proven)",
    `${BASE} Match all lighting, atmosphere, and visual energy to product branding and dominant colors.`,
    [
      "Dark cinematic void! Brand-colored energy effects and volumetric fog roll toward camera! Dramatic lighting pulses! Wide low-angle! Whip pan into Shot 2.",
      "Environment erupts with brand-inspired elements from ground! Debris and particles toward camera! Handheld speed ramp! Smash cut to Shot 3.",
      "Extreme macro on container with condensation! Premium textures, reflections, moisture! Droplet in brand colors! 25% slow motion! Tilt to Shot 4.",
      "Ultra-macro branding through condensation — logo, typography, premium pack! Rim lighting on metal! Push-in to Shot 5.",
      "Dramatic product reveal in branded environment! Low-angle power and freshness! Crane follow into Shot 6.",
      "Bird's-eye view — product centered! Brand energy pulses outward! Slow orbit into Shot 7.",
      "Eye-level orbit — floating droplets, particles, cinematic energy! Steadicam slow-mo ramp into Shot 8.",
      "Macro opening — hand opens container! Vapor and freshness burst! Into Shot 9.",
      "Liquid pours in 20% slow motion! Color, texture, freshness tracked! Into Shot 10.",
      "Final hero — product dominates in fully branded environment! Volumetric light! Hold for impact!",
    ], AUDIO_PREMIUM, "Ultra-realistic luxury beverage ad!"),

  entry("drinks_luxury_bottle_15", "Luxury bottle — premium spirits/water",
    `${BASE} Sophisticated luxury beverage atmosphere with elegant brand colors.`,
    [
      "Black marble surface! Single spotlight! Bottle silhouette emerges from mist! Slow push! Into Shot 2.",
      "Ice crystals form around bottle base! Cold premium atmosphere! Particles sparkle! Into Shot 3.",
      "Macro on glass curvature and liquid color inside! Refraction magic! 25% slow-mo! Tilt to Shot 4.",
      "Label gold foil macro catching light! Push-in to Shot 5.",
      "Bottle hero on reflective surface with bokeh city lights! Crane elegance into Shot 6.",
      "Overhead with citrus, herbs, or ice arranged in brand palette! Orbit into Shot 7.",
      "Pour into crystal glass — liquid ribbon in slow motion! Steadicam into Shot 8.",
      "Condensation bead rolls down bottle neck! Macro ASMR! Into Shot 9.",
      "Cork or cap removal with subtle vapor! Premium moment! Into Shot 10.",
      "Final hero — bottle crowned in light! Luxury perfection hold!",
    ], `${AUDIO_PREMIUM} Elegant pour and glass clink SFX!`, "Premium spirits/water luxury commercial!"),

  entry("drinks_cocktail_15", "Cocktail craft — bar mixology",
    `${BASE} Vibrant bar atmosphere inspired by cocktail colors and ingredients.`,
    [
      "Dark bar ambient glow! Neon accents in brand colors! Shaker enters frame! Whip pan to Shot 2.",
      "Explosive ice splash in slow motion! Colorful liquid arcs! Speed ramp! Into Shot 3.",
      "Macro on garnish, citrus oil spray, or foam texture! Shallow DOF! Into Shot 4.",
      "Close on shaker condensation and bartender hands! Push-in to Shot 5.",
      "Cocktail hero reveal on bar — perfect color gradient! Crane into Shot 6.",
      "Top-down bar flat-lay — ingredients orbit product! Into Shot 7.",
      "Eye-level clink of glasses — celebration energy! Steadicam into Shot 8.",
      "Straw stir with swirling color patterns! Macro into Shot 9.",
      "Final pour completing the drink — slow motion perfection! Into Shot 10.",
      "Hero cocktail dominates frame — bar luxury hold!",
    ], `${AUDIO_PREMIUM} Shaker ice, pour, and bar ambience SFX!`, "Mixology craft cocktail commercial!"),

  entry("drinks_coffee_15", "Artisan coffee — warm craft",
    `${BASE} Warm artisan coffee atmosphere with rich browns and brand tones.`,
    [
      "Steam rises in dark cafe void! Warm amber light builds! Whip to Shot 2.",
      "Coffee beans cascade in slow motion! Rich brown particles! Into Shot 3.",
      "Macro on crema forming on espresso! Texture perfection! 25% slow-mo! Into Shot 4.",
      "Latte art macro — pattern forms in real time! Push-in to Shot 5.",
      "Cup hero on wooden surface with morning light! Crane warmth into Shot 6.",
      "Overhead coffee setup — cup, beans, grinder arranged! Orbit into Shot 7.",
      "Hand wraps around warm cup — cozy premium moment! Steadicam into Shot 8.",
      "Pour milk swirl in slow motion! Macro into Shot 9.",
      "First sip steam release — satisfaction! Into Shot 10.",
      "Final hero cup — artisan coffee perfection hold!",
    ], `${AUDIO_PREMIUM} Grinder, pour, and cafe warmth SFX!`, "Artisan coffee commercial warmth!"),

  entry("drinks_soda_splash_15", "Soda splash — refreshing burst",
    `${BASE} Explosive refreshment energy with vibrant product colors!`,
    [
      "Dark void! Can or bottle explodes with colored liquid energy! Wide impact! Whip to Shot 2.",
      "Massive splash crown in slow motion! Droplets fly toward camera! Into Shot 3.",
      "Macro on carbonation bubbles racing up glass! Freshness! Into Shot 4.",
      "Logo on wet can surface with droplets! Push-in to Shot 5.",
      "Product hero surrounded by fruit slices in brand colors! Crane into Shot 6.",
      "Top-down splash pool with ripples! Orbit into Shot 7.",
      "Ice cubes tumble around product! Steadicam refresh! Into Shot 8.",
      "Tab pull or cap pop — fizz eruption macro! Into Shot 9.",
      "Pour into ice-filled glass — ultimate refresh slow-mo! Into Shot 10.",
      "Final hero — product drenched in freshness light! Hold!",
    ], `${AUDIO_PREMIUM} Fizz, splash, and refresh SFX!`, "High-energy refreshment splash commercial!"),

  entry("drinks_wine_15", "Wine elegance — vineyard luxury",
    `${BASE} Elegant wine atmosphere with deep reds or golden whites from references.`,
    [
      "Vineyard sunset silhouette! Warm golden haze! Bottle emerges! Push-in to Shot 2.",
      "Grape cluster macro with dew drops! Rich color depth! Into Shot 3.",
      "Wine swirl in glass — legs forming on crystal! 25% slow-mo! Into Shot 4.",
      "Cork extraction with subtle pop! Macro elegance! Into Shot 5.",
      "Bottle hero on barrel with candlelight! Crane romance into Shot 6.",
      "Overhead vineyard table setting! Orbit into Shot 7.",
      "Pour ribbon into glass — ruby or gold liquid! Steadicam into Shot 8.",
      "Label macro on bottle in cellar light! Into Shot 9.",
      "Two glasses toast — celebration bokeh! Into Shot 10.",
      "Final hero bottle — vineyard luxury hold!",
    ], `${AUDIO_PREMIUM} Cork pop, pour, and cellar ambience!`, "Premium wine commercial elegance!"),
];

const CARS = [
  entry("cars_night_city_15", "Night city drive — urban automotive",
    `${BASE} Night city environment with reflections matching vehicle color and brand.`,
    [
      "Rain-soaked city street! Headlight beams cut through fog! Wide low-angle! Whip to Shot 2.",
      "Vehicle emerges from darkness — chrome and paint gleaming! Speed ramp! Into Shot 3.",
      "Macro on headlight LED detail or wheel rim! Shallow DOF! Into Shot 4.",
      "Badge or logo macro with rain droplets! Push-in to Shot 5.",
      "Hero front-three-quarter in neon city! Crane power into Shot 6.",
      "Top-down on wet asphalt reflections! Orbit into Shot 7.",
      "Tracking shot alongside moving vehicle — motion blur city! Steadicam into Shot 8.",
      "Door handle or keyless entry touch — premium detail! Macro into Shot 9.",
      "Exhaust or electric light signature in slow motion! Into Shot 10.",
      "Final hero — vehicle owns the night frame! Hold!",
    ], `${AUDIO_PREMIUM} Engine rumble, tire wet road, city ambience!`, "Premium automotive night commercial!"),

  entry("cars_desert_power_15", "Desert power — off-road dominance",
    `${BASE} Desert power atmosphere with dust and golden light matching vehicle.`,
    [
      "Vast desert horizon! Heat shimmer! Vehicle silhouette distant! Push-in to Shot 2.",
      "Dust explosion as vehicle launches! Particles toward camera! Into Shot 3.",
      "Macro on tire tread gripping sand! Technical detail! Into Shot 4.",
      "Grille and badge macro with sand particles! Push-in to Shot 5.",
      "Low-angle hero — vehicle climbing dune! Power and dominance! Crane into Shot 6.",
      "Aerial top-down on desert trail! Orbit into Shot 7.",
      "Tracking dust trail at speed! Steadicam into Shot 8.",
      "Door opens — interior premium detail flash! Into Shot 9.",
      "Sunset silhouette — iconic profile! Slow-mo into Shot 10.",
      "Final hero — desert king hold!",
    ], `${AUDIO_PREMIUM} Engine power, dust impact, desert wind!`, "Off-road automotive power film!"),

  entry("cars_showroom_15", "Showroom reveal — luxury dealership",
    `${BASE} Pristine showroom luxury with controlled lighting on vehicle.`,
    [
      "Dark showroom! Single spotlight sweeps! Vehicle under cover! Push-in to Shot 2.",
      "Cover pulls away in slow motion! Reveal gleaming paint! Into Shot 3.",
      "Macro on paint depth and reflection! Mirror finish! Into Shot 4.",
      "Wheel and caliper macro — engineering beauty! Push-in to Shot 5.",
      "Full vehicle on rotating platform! Crane elegance into Shot 6.",
      "Top-down showroom geometry! Orbit into Shot 7.",
      "Interior through window — premium leather and tech! Steadicam into Shot 8.",
      "Key fob or start button — engine awakens! Macro into Shot 9.",
      "Headlights ignite sequentially! Drama into Shot 10.",
      "Final hero — showroom perfection hold!",
    ], `${AUDIO_PREMIUM} Showroom ambience, cover swoosh, engine start!`, "Luxury dealership reveal commercial!"),

  entry("cars_detail_macro_15", "Engineering detail — precision macro",
    `${BASE} Engineering precision focus on vehicle details and craftsmanship.`,
    [
      "Black studio! Light reveals wheel spoke edge! Push-in to Shot 2.",
      "Sequential macro tour — stitching, carbon fiber, metal finish! Into Shot 3.",
      "Extreme macro on engine component or EV battery design! Into Shot 4.",
      "Badge craftsmanship macro! Push-in to Shot 5.",
      "Full vehicle detail montage accelerating! Crane into Shot 6.",
      "Top-down technical layout! Orbit into Shot 7.",
      "Dashboard UI glow — technology hero! Steadicam into Shot 8.",
      "Steering wheel grip — leather texture macro! Into Shot 9.",
      "Headlight internal optics reveal! Into Shot 10.",
      "Final hero detail composite — engineering art hold!",
    ], `${AUDIO_PREMIUM} Precision mechanical SFX and subtle engine tone!`, "Engineering precision automotive film!"),

  entry("cars_electric_neon_15", "Electric future — neon tech",
    `${BASE} Futuristic electric vehicle atmosphere with neon and tech energy.`,
    [
      "Dark void! Neon lines draw vehicle outline! Electric pulse! Whip to Shot 2.",
      "Vehicle materializes with blue-white energy surge! Into Shot 3.",
      "Macro on charging port glow or LED strip! Tech detail! Into Shot 4.",
      "Digital dashboard animation reflected on paint! Push-in to Shot 5.",
      "Silent speed — vehicle glides through neon tunnel! Crane into Shot 6.",
      "Top-down charging pad glow! Orbit into Shot 7.",
      "Zero-emission vapor or light trail! Steadicam into Shot 8.",
      "App unlock on phone — seamless tech! Macro into Shot 9.",
      "Instant torque launch — silent power! Slow-mo into Shot 10.",
      "Final hero — electric future hold!",
    ], `${AUDIO_PREMIUM} Electronic pulses, subtle motor whine, tech UI sounds!`, "Futuristic EV commercial!"),

  entry("cars_rain_luxury_15", "Rain luxury — reflective elegance",
    `${BASE} Rain-soaked luxury atmosphere emphasizing paint and design lines.`,
    [
      "Rain falls on dark surface! First droplet hits hood! Push-in to Shot 2.",
      "Water beads roll off aerodynamic curves! Paint depth revealed! Into Shot 3.",
      "Macro on droplet reflecting entire vehicle! Into Shot 4.",
      "Wiper reveal — crystal clear view through windshield! Push-in to Shot 5.",
      "Vehicle cuts through rain at speed — spray wings! Crane into Shot 6.",
      "Reflection in puddle — perfect mirror shot! Orbit into Shot 7.",
      "Interior dry luxury contrast with wet exterior! Steadicam into Shot 8.",
      "Hand on wet hood — premium touch! Macro into Shot 9.",
      "Rain clears — sun breaks on paint! Into Shot 10.",
      "Final hero — rain luxury perfection hold!",
    ], `${AUDIO_PREMIUM} Rain, wipers, and refined engine tone!`, "Rain luxury automotive elegance!"),
];

// Continue with remaining categories in part 2 - I'll append in same file

const COSMETICS = [
  entry("cosmetics_serum_15", "Serum drop — skincare science",
    `${BASE} Clean clinical luxury with soft brand-colored lighting.`,
    [
      "White void! Golden drop falls in slow motion! Ripples of light! Push-in to Shot 2.",
      "Serum bottle emerges from liquid surface! Ethereal glow! Into Shot 3.",
      "Macro dropper releasing perfect droplet! Shallow DOF! Into Shot 4.",
      "Ingredient particles swirl in liquid! Push-in to Shot 5.",
      "Bottle hero on glass with botanical elements! Crane into Shot 6.",
      "Top-down skincare ritual layout! Orbit into Shot 7.",
      "Application on skin — dewy glow result! Steadicam into Shot 8.",
      "Texture smear macro — creamy perfection! Into Shot 9.",
      "Mist spray catches light! Into Shot 10.",
      "Final hero bottle — skincare science hold!",
    ], `${AUDIO_PREMIUM} Soft droplet, mist, and spa ambience!`, "Clinical skincare luxury commercial!"),

  entry("cosmetics_lipstick_15", "Lipstick glamour — bold beauty",
    `${BASE} Bold glamour lighting matching lipstick or makeup brand colors.`,
    [
      "Dark studio! Red or brand-colored light slash! Whip to Shot 2.",
      "Lipstick bullet rises from case in slow motion! Sparkle! Into Shot 3.",
      "Macro on lipstick texture and tip! Rich pigment! Into Shot 4.",
      "Application on lips — perfect stroke! Push-in to Shot 5.",
      "Full glamour face reveal — product hero! Crane into Shot 6.",
      "Top-down makeup flat-lay! Orbit into Shot 7.",
      "Mirror dual reflection — beauty power! Steadicam into Shot 8.",
      "Kiss mark or smudge art macro! Into Shot 9.",
      "Wind in hair — confidence slow-mo! Into Shot 10.",
      "Final hero — bold beauty hold!",
    ], `${AUDIO_PREMIUM} Glamour beat with soft cosmetic SFX!`, "High-glamour beauty commercial!"),

  entry("cosmetics_perfume_15", "Perfume mist — fragrance dream",
    `${BASE} Dreamy fragrance atmosphere with mist and brand elegance.`,
    [
      "Soft focus bedroom light! Perfume bottle silhouette! Push-in to Shot 2.",
      "Mist cloud erupts in slow motion — golden particles! Into Shot 3.",
      "Macro on bottle crystal facets! Light refraction! Into Shot 4.",
      "Spray atomization macro — perfect mist cone! Push-in to Shot 5.",
      "Bottle hero in flower field or silk fabric! Crane dream into Shot 6.",
      "Top-down petals arranged around product! Orbit into Shot 7.",
      "Model neck application — elegant gesture! Steadicam into Shot 8.",
      "Cap removal with subtle glass chime! Macro into Shot 9.",
      "Scent trail visualized as light ribbons! Into Shot 10.",
      "Final hero — fragrance dream hold!",
    ], `${AUDIO_PREMIUM} Glass chime, mist spray, dreamy music swell!`, "Luxury fragrance commercial!"),

  entry("cosmetics_palette_15", "Palette reveal — color explosion",
    `${BASE} Vibrant color energy from makeup palette and brand shades.`,
    [
      "Black void! Color powder explosion in brand hues! Whip to Shot 2.",
      "Palette opens — mirrors catch light! Slow motion! Into Shot 3.",
      "Macro on individual eyeshadow pans! Pigment texture! Into Shot 4.",
      "Brush sweep collecting color! Push-in to Shot 5.",
      "Eye makeup reveal — dramatic color story! Crane into Shot 6.",
      "Top-down palette art arrangement! Orbit into Shot 7.",
      "Cheek application glow! Steadicam into Shot 8.",
      "Glitter particle macro catch light! Into Shot 9.",
      "Full face color transformation montage! Into Shot 10.",
      "Final hero palette — color explosion hold!",
    ], AUDIO_PREMIUM, "Vibrant beauty color commercial!"),

  entry("cosmetics_ritual_15", "Skincare ritual — spa calm",
    `${BASE} Calm spa ritual atmosphere with soft natural tones.`,
    [
      "Steam and soft morning light! Bathroom serenity! Push-in to Shot 2.",
      "Hands reach for product on marble shelf! Calm energy! Into Shot 3.",
      "Macro on cream texture scooped! Rich consistency! Into Shot 4.",
      "Gentle face massage application! Push-in to Shot 5.",
      "Product lineup hero on spa tray! Crane calm into Shot 6.",
      "Top-down ritual steps layout! Orbit into Shot 7.",
      "Water splash refresh on face! Steadicam into Shot 8.",
      "Towel reveal — glowing skin result! Into Shot 9.",
      "Candle and product bokeh! Into Shot 10.",
      "Final hero — spa ritual perfection hold!",
    ], `${AUDIO_PREMIUM} Soft water, cream, spa calm ambience!`, "Wellness skincare ritual commercial!"),

  entry("cosmetics_mirror_15", "Mirror glamour — dual reflection",
    `${BASE} Mirror and reflection composition emphasizing beauty product.`,
    [
      "Cracked light on vanity mirror! Product enters reflection first! Push-in to Shot 2.",
      "Dual frame — reality and mirror! Symmetric glamour! Into Shot 3.",
      "Macro on product reflected in mirror with bokeh bulbs! Into Shot 4.",
      "Hand picks up product — both frames sync! Push-in to Shot 5.",
      "Application montage in mirror view! Crane into Shot 6.",
      "Overhead vanity flat-lay! Orbit into Shot 7.",
      "Spin reveal — mirror and face together! Steadicam into Shot 8.",
      "Lip gloss or mascara wand macro! Into Shot 9.",
      "Final confident look into mirror! Slow-mo into Shot 10.",
      "Final hero — mirror glamour hold!",
    ], AUDIO_PREMIUM, "Vanity glamour beauty film!"),
];

const WEBSITES = [
  entry("web_floating_ui_15", "Floating UI — SaaS hero",
    `${BASE} Futuristic digital atmosphere matching app brand colors from screenshots.`,
    [
      "Dark tech void! UI elements float into formation! Glow in brand colors! Whip to Shot 2.",
      "Dashboard screens assemble in 3D space! Particle data streams! Into Shot 3.",
      "Macro on key UI button or feature highlight! Shallow DOF! Into Shot 4.",
      "Logo animation from references! Push-in to Shot 5.",
      "Full app hero on floating device! Crane tech into Shot 6.",
      "Top-down UI component layout! Orbit into Shot 7.",
      "Scroll interaction — smooth feature reveal! Steadicam into Shot 8.",
      "Notification or success state animation! Macro into Shot 9.",
      "Multi-device sync visual! Into Shot 10.",
      "Final hero — app dominates digital space! Hold!",
    ], `${AUDIO_PREMIUM} UI clicks, soft tech whooshes!`, "Premium SaaS product commercial!"),

  entry("web_phone_hero_15", "Phone app — mobile hero",
    `${BASE} Mobile-first hero showcasing app on phone from reference images.`,
    [
      "Hand holds phone from darkness! Screen illuminates face! Push-in to Shot 2.",
      "App interface animates on screen — key features! Into Shot 3.",
      "Macro on screen pixel clarity and UI detail! Into Shot 4.",
      "Finger tap interaction — ripple effect! Push-in to Shot 5.",
      "Phone hero with environment reflecting brand colors! Crane into Shot 6.",
      "Top-down desk setup with phone centered! Orbit into Shot 7.",
      "Swipe gesture in slow motion! Steadicam into Shot 8.",
      "App icon macro on home screen! Into Shot 9.",
      "Success moment — celebration UI! Into Shot 10.",
      "Final hero phone — mobile app hold!",
    ], AUDIO_PREMIUM, "Mobile app launch commercial!"),

  entry("web_dashboard_15", "Dashboard glow — analytics power",
    `${BASE} Professional dashboard and analytics atmosphere from UI references.`,
    [
      "Server room bokeh! Monitor glow builds! Push-in to Shot 2.",
      "Dashboard charts animate upward! Green success energy! Into Shot 3.",
      "Macro on graph line or KPI number! Into Shot 4.",
      "Cursor click on key action button! Push-in to Shot 5.",
      "Multi-monitor command center hero! Crane into Shot 6.",
      "Top-down keyboard and screen layout! Orbit into Shot 7.",
      "Real-time data particles flow! Steadicam into Shot 8.",
      "Team collaboration UI split screen! Into Shot 9.",
      "Export or share success animation! Into Shot 10.",
      "Final hero dashboard — data power hold!",
    ], AUDIO_PREMIUM, "Enterprise SaaS dashboard commercial!"),

  entry("web_device_trio_15", "Device trio — cross-platform",
    `${BASE} Phone, tablet, and desktop showing unified product experience.`,
    [
      "Three devices emerge from light beam! Synchronized screens! Push-in to Shot 2.",
      "Same app flows across devices! Seamless transition! Into Shot 3.",
      "Macro on thinnest device edge — premium hardware! Into Shot 4.",
      "Sync animation connecting devices! Push-in to Shot 5.",
      "Hero trio on minimal desk! Crane into Shot 6.",
      "Top-down device arrangement! Orbit into Shot 7.",
      "User picks up phone — continuity from desktop! Steadicam into Shot 8.",
      "Cloud sync icon animation! Into Shot 9.",
      "All screens show success state together! Into Shot 10.",
      "Final hero — cross-platform hold!",
    ], AUDIO_PREMIUM, "Cross-platform product commercial!"),

  entry("web_neon_tech_15", "Neon tech — startup energy",
    `${BASE} Neon startup energy with bold tech brand colors from references.`,
    [
      "Black void! Neon wireframe draws product UI! Electric pulse! Whip to Shot 2.",
      "Interface explodes into full color! Startup energy! Into Shot 3.",
      "Macro on code or feature highlight glowing! Into Shot 4.",
      "Logo neon sign flickers on! Push-in to Shot 5.",
      "Laptop hero in neon-lit workspace! Crane into Shot 6.",
      "Top-down hacker aesthetic desk! Orbit into Shot 7.",
      "Fast feature montage with beat sync! Steadicam into Shot 8.",
      "Rocket launch or growth graph animation! Into Shot 9.",
      "Team high-five reflected in screen! Into Shot 10.",
      "Final hero — neon startup hold!",
    ], `${AUDIO_PREMIUM} Electronic startup energy beats!`, "Startup tech launch commercial!"),

  entry("web_website_scroll_15", "Website scroll — landing page",
    `${BASE} Landing page scroll experience from website screenshot references.`,
    [
      "Browser frame emerges! URL bar glows! Push-in to Shot 2.",
      "Smooth scroll reveals hero section! Parallax depth! Into Shot 3.",
      "Macro on CTA button and typography! Into Shot 4.",
      "Hover animation on key element! Push-in to Shot 5.",
      "Full page hero on large display! Crane into Shot 6.",
      "Top-down laptop with perfect page layout! Orbit into Shot 7.",
      "Mobile responsive resize animation! Steadicam into Shot 8.",
      "Testimonial or stats counter animate! Into Shot 9.",
      "Form submit success state! Into Shot 10.",
      "Final hero — website perfection hold!",
    ], AUDIO_PREMIUM, "Website landing page commercial!"),
];

const FOOD = [
  entry("food_steam_hero_15", "Steam hero — hot dish reveal",
    `${BASE} Appetizing steam and warmth matching dish colors from references.`,
    [
      "Dark kitchen void! Steam cloud builds! Dish silhouette inside! Push-in to Shot 2.",
      "Steam clears revealing colorful dish! Appetite trigger! Into Shot 3.",
      "Macro on glistening sauce or melted cheese! Shallow DOF! Into Shot 4.",
      "Fresh herb garnish falls in slow motion! Push-in to Shot 5.",
      "Full plate hero on rustic table! Crane warmth into Shot 6.",
      "Top-down food styling perfection! Orbit into Shot 7.",
      "Fork lift — cheese pull or juice drip! Steadicam into Shot 8.",
      "Sizzle sound moment — oil sparkle macro! Into Shot 9.",
      "Chef hands plate the dish! Into Shot 10.",
      "Final hero — steam appetite hold!",
    ], `${AUDIO_PREMIUM} Sizzle, steam, kitchen ambience!`, "Appetizing food hero commercial!"),

  entry("food_ingredient_burst_15", "Ingredient burst — fresh explosion",
    `${BASE} Fresh ingredient explosion in brand-relevant colors.`,
    [
      "Black void! Ingredients explode outward from center! Slow motion! Whip to Shot 2.",
      "Each ingredient orbits dish formation! Vibrant colors! Into Shot 3.",
      "Macro on fresh cut surface — juice and texture! Into Shot 4.",
      "Spice or seasoning cloud burst! Push-in to Shot 5.",
      "Assembled dish hero from above! Crane into Shot 6.",
      "Top-down ingredient mandala! Orbit into Shot 7.",
      "Flame kiss or grill mark moment! Steadicam into Shot 8.",
      "Oil pour golden slow motion! Macro into Shot 9.",
      "Final garnish drop! Into Shot 10.",
      "Final hero — ingredient explosion hold!",
    ], AUDIO_PREMIUM, "Fresh ingredient food commercial!"),

  entry("food_chef_hands_15", "Chef hands — artisan craft",
    `${BASE} Artisan chef craftsmanship atmosphere.`,
    [
      "Flour dust in warm kitchen light! Hands enter frame kneading! Push-in to Shot 2.",
      "Precision knife work — fresh ingredients! Speed ramp! Into Shot 3.",
      "Macro on hands shaping dish with care! Into Shot 4.",
      "Seasoning pinch falling in slow motion! Push-in to Shot 5.",
      "Plated dish presented with pride! Crane into Shot 6.",
      "Top-down chef workspace! Orbit into Shot 7.",
      "Flame wok toss or oven open! Steadicam into Shot 8.",
      "Tasting moment — satisfaction! Into Shot 9.",
      "Steam rise from finished plate! Into Shot 10.",
      "Final hero — chef artisan hold!",
    ], `${AUDIO_PREMIUM} Knife, sizzle, kitchen craft SFX!`, "Artisan chef food commercial!"),

  entry("food_dessert_15", "Dessert macro — sweet indulgence",
    `${BASE} Indulgent dessert atmosphere with rich colors and textures.`,
    [
      "Dark backdrop! Chocolate drizzle falls! Slow motion! Push-in to Shot 2.",
      "Dessert assembled layer by layer! Decadence! Into Shot 3.",
      "Macro on chocolate crack or cream swirl! Into Shot 4.",
      "Berry or topping drop onto surface! Push-in to Shot 5.",
      "Full dessert hero with bokeh lights! Crane into Shot 6.",
      "Top-down patisserie art! Orbit into Shot 7.",
      "Fork cuts through — perfect interior reveal! Steadicam into Shot 8.",
      "Powdered sugar dust cloud! Macro into Shot 9.",
      "Candle or flame on dessert! Into Shot 10.",
      "Final hero — sweet indulgence hold!",
    ], AUDIO_PREMIUM, "Decadent dessert commercial!"),

  entry("food_burger_build_15", "Burger build — layer stack",
    `${BASE} Bold burger build with juicy textures and brand colors.`,
    [
      "Dark void! Bottom bun lands! Impact dust! Whip to Shot 2.",
      "Each layer stacks in slow motion — patty, cheese, veg! Into Shot 3.",
      "Macro on melting cheese and juice! Into Shot 4.",
      "Sauce drip perfection! Push-in to Shot 5.",
      "Complete burger hero — towering! Crane into Shot 6.",
      "Top-down cross-section reveal! Orbit into Shot 7.",
      "Grill flame kiss on patty! Steadicam into Shot 8.",
      "Hands pick up burger — bite anticipation! Into Shot 9.",
      "Sesame seed bun macro! Into Shot 10.",
      "Final hero burger — appetite hold!",
    ], `${AUDIO_PREMIUM} Grill sizzle, stack impacts!`, "Bold burger commercial!"),

  entry("food_farm_fresh_15", "Farm fresh — natural origin",
    `${BASE} Farm-fresh natural atmosphere with organic colors.`,
    [
      "Sunrise over field! Dew on produce! Push-in to Shot 2.",
      "Hands harvest fresh ingredient! Golden light! Into Shot 3.",
      "Macro on water droplets on vegetable or fruit! Into Shot 4.",
      "Basket of fresh produce arranged! Push-in to Shot 5.",
      "Dish hero with farm ingredients visible! Crane into Shot 6.",
      "Top-down farm-to-table layout! Orbit into Shot 7.",
      "Wash and prep in clean water! Steadicam into Shot 8.",
      "Cutting board fresh slice! Macro into Shot 9.",
      "Family table setting warmth! Into Shot 10.",
      "Final hero — farm fresh hold!",
    ], `${AUDIO_PREMIUM} Nature, water, rustic kitchen ambience!`, "Farm-to-table food commercial!"),
];

const JEWELRY = [
  entry("jewelry_light_prism_15", "Light prism — refraction magic",
    `${BASE} Light refraction and sparkle matching metal and gem from references.`,
    [
      "Dark void! Light beam hits gem — rainbow explosion! Push-in to Shot 2.",
      "Prism colors dance across frame! Sparkle particles! Into Shot 3.",
      "Extreme macro on facet cuts! Fire and brilliance! Into Shot 4.",
      "Metal setting detail macro! Push-in to Shot 5.",
      "Full piece hero on black velvet! Crane into Shot 6.",
      "Top-down gem geometry! Orbit into Shot 7.",
      "Light orbit around piece — continuous sparkle! Steadicam into Shot 8.",
      "Box opens — reveal moment! Macro into Shot 9.",
      "On skin — elegance close-up! Into Shot 10.",
      "Final hero — light prism hold!",
    ], `${AUDIO_PREMIUM} Crystal chime and sparkle shimmer!`, "Luxury jewelry refraction film!"),

  entry("jewelry_velvet_15", "Velvet reveal — box opening",
    `${BASE} Velvet and luxury packaging atmosphere.`,
    [
      "Closed luxury box on velvet! Spotlight! Push-in to Shot 2.",
      "Lid opens slowly — light floods interior! Into Shot 3.",
      "Macro on satin interior and piece nestled! Into Shot 4.",
      "Gloved hands lift piece! Push-in to Shot 5.",
      "Hero on velvet pedestal! Crane into Shot 6.",
      "Top-down box and piece composition! Orbit into Shot 7.",
      "Neck or wrist placement — elegance! Steadicam into Shot 8.",
      "Clasp or chain detail macro! Into Shot 9.",
      "Box closes — enigmatic tease! Into Shot 10.",
      "Final hero — velvet luxury hold!",
    ], AUDIO_PREMIUM, "Luxury unboxing jewelry commercial!"),

  entry("jewelry_diamond_macro_15", "Diamond macro — extreme brilliance",
    `${BASE} Extreme gem brilliance and clarity from reference piece.`,
    [
      "Absolute black! Single point light! Diamond edge appears! Push-in to Shot 2.",
      "Light enters stone — internal fire explodes! Into Shot 3.",
      "Extreme macro on table, crown, pavilion! Into Shot 4.",
      "Inclusion-free clarity showcase! Push-in to Shot 5.",
      "Ring or necklace hero rotation! Crane into Shot 6.",
      "Top-down symmetry perfection! Orbit into Shot 7.",
      "Comparison scale flash — carat hero! Steadicam into Shot 8.",
      "Proposal hand moment hint! Macro into Shot 9.",
      "Sparkle cascade time-lapse! Into Shot 10.",
      "Final hero — diamond brilliance hold!",
    ], AUDIO_PREMIUM, "High-jewelry diamond commercial!"),

  entry("jewelry_wrist_glamour_15", "Wrist glamour — watch & bracelet",
    `${BASE} Wrist glamour for watches and bracelets from references.`,
    [
      "Dark club bokeh! Wrist enters frame! Push-in to Shot 2.",
      "Watch face catches light — dial detail! Into Shot 3.",
      "Macro on mechanism or bracelet link! Into Shot 4.",
      "Second hand sweep in slow motion! Push-in to Shot 5.",
      "Full wrist hero — confident gesture! Crane into Shot 6.",
      "Top-down watch flat-lay! Orbit into Shot 7.",
      "Adjustment clasp — precision! Steadicam into Shot 8.",
      "Reflection in glass surface! Macro into Shot 9.",
      "Night drive steering wheel wrist shot! Into Shot 10.",
      "Final hero — wrist glamour hold!",
    ], AUDIO_PREMIUM, "Luxury watch commercial!"),

  entry("jewelry_pedestal_spin_15", "Pedestal spin — gallery display",
    `${BASE} Gallery display elegance on rotating pedestal.`,
    [
      "Museum dark! Pedestal rises! Push-in to Shot 2.",
      "Piece placed — rotation begins! Gallery spotlight! Into Shot 3.",
      "Macro during rotation — every angle! Into Shot 4.",
      "Laser guide light on gem! Push-in to Shot 5.",
      "Full rotation hero — 360 perfection! Crane into Shot 6.",
      "Top-down pedestal geometry! Orbit into Shot 7.",
      "Zoom through gem center! Steadicam into Shot 8.",
      "Security glass reflection art! Into Shot 9.",
      "Applause silhouette blur background! Into Shot 10.",
      "Final hero — gallery spin hold!",
    ], AUDIO_PREMIUM, "Gallery jewelry display film!"),

  entry("jewelry_black_luxury_15", "Black luxury — minimal elegance",
    `${BASE} Minimal black-background luxury emphasizing piece design.`,
    [
      "Pure black! Thin light line draws piece outline! Push-in to Shot 2.",
      "Piece materializes from line — minimal drama! Into Shot 3.",
      "Macro on single design detail! Into Shot 4.",
      "Shadow play on metal curves! Push-in to Shot 5.",
      "Centered hero — maximum negative space! Crane into Shot 6.",
      "Top-down minimal composition! Orbit into Shot 7.",
      "Side profile silhouette elegance! Steadicam into Shot 8.",
      "Light sweep across surface! Macro into Shot 9.",
      "Piece on model — single spotlight! Into Shot 10.",
      "Final hero — black luxury hold!",
    ], AUDIO_PREMIUM, "Minimal high-jewelry commercial!"),
];

const REAL_ESTATE = [
  entry("re_drone_arrival_15", "Drone arrival — property approach",
    `${BASE} Aerial property approach from reference images.`,
    [
      "Aerial wide — neighborhood context! Golden hour! Push-in to Shot 2.",
      "Drone descends toward property! Smooth cinematic approach! Into Shot 3.",
      "Macro on architectural detail — stone, wood, glass! Into Shot 4.",
      "Front door or entrance hero! Push-in to Shot 5.",
      "Property hero exterior — full facade! Crane into Shot 6.",
      "Top-down roof and garden layout! Orbit into Shot 7.",
      "Pool or terrace reveal! Steadicam into Shot 8.",
      "Window reflection of landscape! Macro into Shot 9.",
      "Driveway arrival perspective! Into Shot 10.",
      "Final hero — property arrival hold!",
    ], `${AUDIO_PREMIUM} Subtle drone wind, luxury ambience!`, "Luxury real estate aerial commercial!"),

  entry("re_interior_walk_15", "Interior walk — room flow",
    `${BASE} Interior walkthrough feel from reference photos.`,
    [
      "Front door opens — light floods interior! Push-in to Shot 2.",
      "Smooth glide through hallway! Warm tones! Into Shot 3.",
      "Macro on premium finish — marble, hardwood! Into Shot 4.",
      "Living room reveal — spacious hero! Push-in to Shot 5.",
      "Kitchen island hero — designer details! Crane into Shot 6.",
      "Top-down room layout! Orbit into Shot 7.",
      "Bedroom sanctuary soft light! Steadicam into Shot 8.",
      "Bathroom spa detail macro! Into Shot 9.",
      "Balcony door opens to view! Into Shot 10.",
      "Final hero — interior luxury hold!",
    ], AUDIO_PREMIUM, "Luxury interior walkthrough film!"),

  entry("re_golden_exterior_15", "Golden hour — exterior glow",
    `${BASE} Golden hour exterior warmth from property references.`,
    [
      "Sun low on horizon! Property silhouette! Push-in to Shot 2.",
      "Golden light washes facade! Warm glow! Into Shot 3.",
      "Macro on window catching sunset! Into Shot 4.",
      "Garden flowers in foreground bokeh! Push-in to Shot 5.",
      "Full exterior hero — golden perfection! Crane into Shot 6.",
      "Top-down property and landscape! Orbit into Shot 7.",
      "Outdoor dining setup lifestyle! Steadicam into Shot 8.",
      "Fire pit or outdoor feature! Macro into Shot 9.",
      "Family silhouette on porch! Into Shot 10.",
      "Final hero — golden exterior hold!",
    ], AUDIO_PREMIUM, "Golden hour property commercial!"),

  entry("re_pool_lifestyle_15", "Pool lifestyle — resort living",
    `${BASE} Resort pool lifestyle from property references.`,
    [
      "Water surface ripple! Pool emerges! Push-in to Shot 2.",
      "Sunlight dances on water! Luxury resort feel! Into Shot 3.",
      "Macro on pool tile and water clarity! Into Shot 4.",
      "Lounger and umbrella styling! Push-in to Shot 5.",
      "Pool and house hero composition! Crane into Shot 6.",
      "Top-down pool geometry! Orbit into Shot 7.",
      "Dive or splash lifestyle hint! Steadicam into Shot 8.",
      "Cocktail on pool edge macro! Into Shot 9.",
      "Night pool lighting glow! Into Shot 10.",
      "Final hero — pool lifestyle hold!",
    ], AUDIO_PREMIUM, "Resort pool lifestyle commercial!"),

  entry("re_kitchen_hero_15", "Kitchen hero — designer heart",
    `${BASE} Designer kitchen focus from interior references.`,
    [
      "Dark kitchen! Under-cabinet lights ignite! Push-in to Shot 2.",
      "Island centerpiece revealed! Premium materials! Into Shot 3.",
      "Macro on countertop stone veining! Into Shot 4.",
      "Faucet water flow elegance! Push-in to Shot 5.",
      "Full kitchen hero — open concept! Crane into Shot 6.",
      "Top-down island layout! Orbit into Shot 7.",
      "Appliance premium detail! Steadicam into Shot 8.",
      "Coffee moment lifestyle! Macro into Shot 9.",
      "Family gathering warm light! Into Shot 10.",
      "Final hero — designer kitchen hold!",
    ], AUDIO_PREMIUM, "Designer kitchen commercial!"),

  entry("re_balcony_view_15", "Balcony view — panorama lifestyle",
    `${BASE} Panoramic view from balcony or terrace references.`,
    [
      "Balcony doors closed — city or sea blur beyond! Push-in to Shot 2.",
      "Doors open — view explodes! Wind and light! Into Shot 3.",
      "Macro on railing material and design! Into Shot 4.",
      "Outdoor furniture styling! Push-in to Shot 5.",
      "Person on balcony admiring view — lifestyle! Crane into Shot 6.",
      "Top-down balcony layout! Orbit into Shot 7.",
      "Sunset timelapse on view! Steadicam into Shot 8.",
      "Morning coffee on balcony! Macro into Shot 9.",
      "Night city lights panorama! Into Shot 10.",
      "Final hero — balcony view hold!",
    ], AUDIO_PREMIUM, "Panoramic view property commercial!"),
];

const GAMING = [
  entry("gaming_rgb_station_15", "RGB battle station — setup hero",
    `${BASE} RGB gaming setup energy matching product colors from references.`,
    [
      "Dark room! RGB strips ignite in sequence! Push-in to Shot 2.",
      "Full battle station assembles! Neon glow! Into Shot 3.",
      "Macro on keyboard switch or mouse sensor! Into Shot 4.",
      "Monitor displays epic game scene! Push-in to Shot 5.",
      "Complete setup hero — immersive glow! Crane into Shot 6.",
      "Top-down desk layout perfection! Orbit into Shot 7.",
      "Headset drop onto stand! Steadicam into Shot 8.",
      "Controller button macro RGB pulse! Into Shot 9.",
      "Victory moment on screen reflection! Into Shot 10.",
      "Final hero — RGB station hold!",
    ], `${AUDIO_PREMIUM} Mechanical keyboard, game audio hits!`, "RGB gaming setup commercial!"),

  entry("gaming_controller_15", "Controller macro — precision gear",
    `${BASE} Controller and peripheral precision from product references.`,
    [
      "Black void! Controller falls into frame! Impact light! Whip to Shot 2.",
      "Button press sequence in macro! RGB feedback! Into Shot 3.",
      "Grip texture extreme close-up! Into Shot 4.",
      "Trigger slow press — precision! Push-in to Shot 5.",
      "Controller hero with game bokeh! Crane into Shot 6.",
      "Top-down controller symmetry! Orbit into Shot 7.",
      "Hands grip — esports intensity! Steadicam into Shot 8.",
      "Wireless connect pulse! Macro into Shot 9.",
      "Combo move on screen match! Into Shot 10.",
      "Final hero — controller precision hold!",
    ], AUDIO_PREMIUM, "Gaming peripheral commercial!"),

  entry("gaming_esports_15", "Esports arena — competitive energy",
    `${BASE} Esports arena energy for gaming products.`,
    [
      "Arena dark! Crowd roar light pulse! Push-in to Shot 2.",
      "Player silhouette at setup! Dramatic backlight! Into Shot 3.",
      "Macro on product with arena reflection! Into Shot 4.",
      "Intense gameplay hands! Push-in to Shot 5.",
      "Product hero on stage podium! Crane into Shot 6.",
      "Top-down tournament layout! Orbit into Shot 7.",
      "Victory moment — confetti and RGB! Steadicam into Shot 8.",
      "Team jersey and gear detail! Into Shot 9.",
      "Trophy reflection in monitor! Into Shot 10.",
      "Final hero — esports energy hold!",
    ], `${AUDIO_PREMIUM} Crowd roar, game impacts, victory swell!`, "Esports gaming commercial!"),

  entry("gaming_unboxing_15", "Unboxing reveal — product launch",
    `${BASE} Exciting unboxing reveal for gaming product.`,
    [
      "Sealed box on dark surface! Hype energy! Push-in to Shot 2.",
      "Box opens — light burst from inside! Into Shot 3.",
      "Macro on packaging art and product tease! Into Shot 4.",
      "Protective wrap removed! Push-in to Shot 5.",
      "Product hero lift from box! Crane into Shot 6.",
      "Top-down unboxing layout! Orbit into Shot 7.",
      "First power-on glow! Steadicam into Shot 8.",
      "Accessories laid out macro! Into Shot 9.",
      "Setup montage acceleration! Into Shot 10.",
      "Final hero — unboxing reveal hold!",
    ], AUDIO_PREMIUM, "Unboxing hype gaming commercial!"),

  entry("gaming_screen_glow_15", "Screen glow — immersion",
    `${BASE} Screen glow immersion highlighting gaming product.`,
    [
      "Dark room! Only screen glow on face! Push-in to Shot 2.",
      "Game world colors reflect on product! Into Shot 3.",
      "Macro on screen pixel and product logo! Into Shot 4.",
      "Intensity builds — faster gameplay! Push-in to Shot 5.",
      "Product between player and screen — bridge! Crane into Shot 6.",
      "Top-down immersion setup! Orbit into Shot 7.",
      "Headset activates — audio visualization! Steadicam into Shot 8.",
      "Mouse swipe precision macro! Into Shot 9.",
      "Epic game moment freeze! Into Shot 10.",
      "Final hero — screen glow hold!",
    ], AUDIO_PREMIUM, "Immersive gaming commercial!"),

  entry("gaming_peripheral_lineup_15", "Peripheral lineup — full ecosystem",
    `${BASE} Full gaming peripheral ecosystem from reference images.`,
    [
      "Dark stage! First peripheral spotlights on! Push-in to Shot 2.",
      "Each product joins lineup in sequence! RGB sync! Into Shot 3.",
      "Macro tour across each device! Into Shot 4.",
      "Brand logo sync pulse! Push-in to Shot 5.",
      "Full lineup hero — ecosystem power! Crane into Shot 6.",
      "Top-down product family! Orbit into Shot 7.",
      "Cable management clean aesthetic! Steadicam into Shot 8.",
      "Cross-device compatibility animation! Into Shot 9.",
      "Gamer selects from lineup! Into Shot 10.",
      "Final hero — ecosystem hold!",
    ], AUDIO_PREMIUM, "Gaming ecosystem commercial!"),
];

const GENERAL = [
  entry("general_hero_power_15", "Universal hero — premium power",
    `${BASE} Adapt environment, lighting, and energy to whatever the product is — colors and identity from references!`,
    [
      "Dark cinematic void! Brand-colored energy effects emerge! Volumetric fog toward camera! Wide low-angle! Whip pan to Shot 2.",
      "Environment erupts with particles matching product identity! Handheld speed ramp! Smash cut to Shot 3.",
      "Extreme macro on product surface texture and material quality! Shallow DOF! 25% slow motion! Tilt to Shot 4.",
      "Branding or key detail macro with rim light! Push-in to Shot 5.",
      "Dramatic product reveal in environment inspired by its identity! Low-angle power! Crane into Shot 6.",
      "Bird's-eye view — product centered! Energy pulses outward! Orbit into Shot 7.",
      "Eye-level orbit — floating particles and cinematic atmosphere! Steadicam into Shot 8.",
      "Interactive moment — hands or action showing product use! Macro into Shot 9.",
      "Dynamic product demonstration in slow motion! Into Shot 10.",
      "Final hero — product dominates frame! Volumetric light! Maximum impact hold!",
    ], AUDIO_PREMIUM, "Universal premium product commercial!"),

  entry("general_minimal_15", "Minimal premium — clean studio",
    `${BASE} Clean minimal studio showcasing product design from references.`,
    [
      "Pure white or black studio! Product enters on plinth! Push-in to Shot 2.",
      "Soft shadow and single key light! Elegance! Into Shot 3.",
      "Macro on product finest detail! Into Shot 4.",
      "Slow 360 rotation! Push-in to Shot 5.",
      "Hero centered — maximum negative space! Crane into Shot 6.",
      "Top-down geometric composition! Orbit into Shot 7.",
      "Side profile silhouette! Steadicam into Shot 8.",
      "Material texture close-up! Macro into Shot 9.",
      "Scale context hint — hand or environment! Into Shot 10.",
      "Final hero — minimal perfection hold!",
    ], `${AUDIO_PREMIUM} Clean subtle transitions!`, "Minimal studio product commercial!"),

  entry("general_lifestyle_15", "Lifestyle context — real world",
    `${BASE} Real-world lifestyle context adapted to product type from references.`,
    [
      "Blurred lifestyle environment! Product sharp in foreground! Push-in to Shot 2.",
      "Context reveals — appropriate setting for this product! Into Shot 3.",
      "Macro on product in natural use context! Into Shot 4.",
      "Human interaction hint — hands, silhouette! Push-in to Shot 5.",
      "Product hero in lifestyle scene! Crane into Shot 6.",
      "Top-down scene composition! Orbit into Shot 7.",
      "Morning or golden hour warmth! Steadicam into Shot 8.",
      "Detail moment — authentic use! Macro into Shot 9.",
      "Emotional payoff — satisfaction! Into Shot 10.",
      "Final hero — lifestyle hold!",
    ], AUDIO_PREMIUM, "Lifestyle product commercial!"),

  entry("general_particle_drama_15", "Particle drama — dynamic energy",
    `${BASE} Dynamic particle energy in colors extracted from product references!`,
    [
      "Void! Particle storm in product colors! Explosion toward camera! Whip to Shot 2.",
      "Product forms from particles! Magic assembly! Into Shot 3.",
      "Macro as particles settle on surface! Into Shot 4.",
      "Energy ring pulses around product! Push-in to Shot 5.",
      "Hero with particle orbit! Crane into Shot 6.",
      "Top-down particle mandala! Orbit into Shot 7.",
      "Slow-mo particle burst on interaction! Steadicam into Shot 8.",
      "Light trail encircles product! Macro into Shot 9.",
      "Particle collapse into final form! Into Shot 10.",
      "Final hero — particle drama hold!",
    ], AUDIO_PREMIUM, "Dynamic particle product commercial!"),

  entry("general_dark_luxury_15", "Dark luxury — premium mystery",
    `${BASE} Dark luxury atmosphere with premium mystery for any high-end product.`,
    [
      "Absolute darkness! Thin light reveals product edge! Push-in to Shot 2.",
      "Spotlight expands — premium reveal! Smoke wisps! Into Shot 3.",
      "Macro on finest craftsmanship detail! Into Shot 4.",
      "Reflection on black glass surface! Push-in to Shot 5.",
      "Full product hero — dark luxury! Crane into Shot 6.",
      "Top-down black-on-black composition! Orbit into Shot 7.",
      "Light sweep across contours! Steadicam into Shot 8.",
      "Premium material glint! Macro into Shot 9.",
      "Mystery silhouette then full reveal! Into Shot 10.",
      "Final hero — dark luxury hold!",
    ], AUDIO_PREMIUM, "Dark luxury universal commercial!"),

  entry("general_nature_fresh_15", "Nature fresh — organic clean",
    `${BASE} Fresh natural atmosphere adapted to organic, pet, or outdoor products from references.`,
    [
      "Sunrise nature bokeh! Product on natural surface! Push-in to Shot 2.",
      "Wind moves leaves or natural elements! Fresh energy! Into Shot 3.",
      "Macro on product with natural texture contrast! Into Shot 4.",
      "Water droplet or dew freshness! Push-in to Shot 5.",
      "Product hero in nature setting matching its identity! Crane into Shot 6.",
      "Top-down natural props arrangement! Orbit into Shot 7.",
      "Animal, person, or organic context if relevant! Steadicam into Shot 8.",
      "Hands gently interact — care and trust! Macro into Shot 9.",
      "Golden light breakthrough! Into Shot 10.",
      "Final hero — nature fresh hold!",
    ], `${AUDIO_PREMIUM} Nature ambience, birds, gentle wind!`, "Fresh natural product commercial — works for pets, organic goods, and more!"),
];

const PROMPTS_BY_CATEGORY = {
  fashion: FASHION,
  drinks: DRINKS,
  cars: CARS,
  cosmetics: COSMETICS,
  websites: WEBSITES,
  food: FOOD,
  jewelry: JEWELRY,
  realEstate: REAL_ESTATE,
  gaming: GAMING,
  general: GENERAL,
};

function allPromptEntries() {
  return Object.values(PROMPTS_BY_CATEGORY).flat();
}

module.exports = {
  PROMPTS_BY_CATEGORY,
  allPromptEntries,
};
