/**
 * Capas estáticas para a grelha «Estilos prontos» (Estúdio).
 *
 * Homens: PDF em ordem sequencial (pág. 1 = 1.º card esq. na 1.ª linha da grelha 2 colunas).
 *
 * Mulheres: PDF em ordem sequencial; as duas últimas páginas estavam trocadas (espelho vs fitness)
 * — ficheiros `wom_mirror_concrete` / `wom_fitness_split` corrigidos.
 *
 * Unissex: JPG em `padrao-covers` (lote gerado); estilos listados na API sem ficheiro aqui = gradiente no card.
 *
 * Casais: ref mulher+homem compostos lado a lado (`scripts/generate-couple-covers.mjs`).
 *
 * Comics: só ref homem — 7 páginas (`scripts/generate-comic-covers.mjs`).
 *
 * Sensual: só ref mulher — 11 estilos sn_* (`scripts/generate-sensual-covers.mjs`).
 *
 * Stories: ref mulher — 3 posts editoriais st_* (`scripts/generate-stories-covers.mjs`).
 */
export const PADRAO_STYLE_COVER_BY_ID = {
  men_underwater: "/images/padrao-covers/men_underwater.jpg",
  men_luxury: "/images/padrao-covers/men_luxury.jpg",
  men_lowkey: "/images/padrao-covers/men_lowkey.jpg",
  men_redstudio: "/images/padrao-covers/men_redstudio.jpg",
  men_darkhero: "/images/padrao-covers/men_darkhero.jpg",
  wom_baton: "/images/padrao-covers/wom_baton.jpg",
  wom_coffee: "/images/padrao-covers/wom_coffee.jpg",
  wom_mirror: "/images/padrao-covers/wom_mirror.jpg",
  wom_softselfie: "/images/padrao-covers/wom_softselfie.jpg",
  wom_mirror_concrete: "/images/padrao-covers/wom_mirror_concrete.jpg",
  wom_fitness_split: "/images/padrao-covers/wom_fitness_split.jpg",
  fl_general: "/images/padrao-covers/fl_general.jpg",
  fl_tech: "/images/padrao-covers/fl_tech.jpg",
  fl_corporate: "/images/padrao-covers/fl_corporate.jpg",
  fl_fitness: "/images/padrao-covers/fl_fitness.jpg",
  fl_restaurant: "/images/padrao-covers/fl_restaurant.jpg",
  fl_creative: "/images/padrao-covers/fl_creative.jpg",
  co_polaroid_classic: "/images/padrao-covers/co_polaroid_classic.jpg",
  co_polaroid_romantic: "/images/padrao-covers/co_polaroid_romantic.jpg",
  co_polaroid_playful: "/images/padrao-covers/co_polaroid_playful.jpg",
  x_a_p1: "/images/padrao-covers/x_a_p1.jpg",
  x_a_p2: "/images/padrao-covers/x_a_p2.jpg",
  x_b_p1: "/images/padrao-covers/x_b_p1.jpg",
  x_b_p2: "/images/padrao-covers/x_b_p2.jpg",
  x_b_p3: "/images/padrao-covers/x_b_p3.jpg",
  x_b_p4: "/images/padrao-covers/x_b_p4.jpg",
  x_b_p5: "/images/padrao-covers/x_b_p5.jpg",
  sn_postshower: "/images/padrao-covers/sn_postshower.jpg",
  sn_bedroom: "/images/padrao-covers/sn_bedroom.jpg",
  sn_dark_asteric: "/images/padrao-covers/sn_dark_asteric.jpg",
  sn_minimal: "/images/padrao-covers/sn_minimal.jpg",
  sn_mirror_gaming: "/images/padrao-covers/sn_mirror_gaming.jpg",
  sn_actress: "/images/padrao-covers/sn_actress.jpg",
  sn_lux_mirror: "/images/padrao-covers/sn_lux_mirror.jpg",
  sn_softglam: "/images/padrao-covers/sn_softglam.jpg",
  sn_clean_jumpsuit: "/images/padrao-covers/sn_clean_jumpsuit.jpg",
  sn_high_impact: "/images/padrao-covers/sn_high_impact.jpg",
  sn_street_edge: "/images/padrao-covers/sn_street_edge.jpg",
  st_awareness: "/images/padrao-covers/st_awareness.jpg",
  st_testimonial: "/images/padrao-covers/st_testimonial.jpg",
  st_wellness: "/images/padrao-covers/st_wellness.jpg",
  u_bw_chiar: "/images/padrao-covers/u_bw_chiar.jpg",
  u_bw_hard: "/images/padrao-covers/u_bw_hard.jpg",
  u_bw_intro: "/images/padrao-covers/u_bw_intro.jpg",
  u_bw_soft: "/images/padrao-covers/u_bw_soft.jpg",
  u_corporate: "/images/padrao-covers/u_corporate.jpg",
  u_cr_dom: "/images/padrao-covers/u_cr_dom.jpg",
  u_cr_glow: "/images/padrao-covers/u_cr_glow.jpg",
  u_cr_shad: "/images/padrao-covers/u_cr_shad.jpg",
  u_ed_future: "/images/padrao-covers/u_ed_future.jpg",
  u_ed_modern: "/images/padrao-covers/u_ed_modern.jpg",
  u_em_analog: "/images/padrao-covers/u_em_analog.jpg",
  u_em_break: "/images/padrao-covers/u_em_break.jpg",
  u_em_hard: "/images/padrao-covers/u_em_hard.jpg",
  u_ep_grid_classic: "/images/padrao-covers/u_ep_grid_classic.jpg",
  u_ep_grid_dark: "/images/padrao-covers/u_ep_grid_dark.jpg",
  u_ep_grid_lux: "/images/padrao-covers/u_ep_grid_lux.jpg",
  u_ep_grid_street: "/images/padrao-covers/u_ep_grid_street.jpg",
  u_ep_sorcerer: "/images/padrao-covers/u_ep_sorcerer.jpg",
  u_facepost: "/images/padrao-covers/u_facepost.jpg",
  u_he_cine: "/images/padrao-covers/u_he_cine.jpg",
  u_hk_noir: "/images/padrao-covers/u_hk_noir.jpg",
  u_hk_rain: "/images/padrao-covers/u_hk_rain.jpg",
  u_hk_surv: "/images/padrao-covers/u_hk_surv.jpg",
  u_joker: "/images/padrao-covers/u_joker.jpg",
  u_lion_desert: "/images/padrao-covers/u_lion_desert.jpg",
  u_lion_shadow: "/images/padrao-covers/u_lion_shadow.jpg",
  u_lion_winter: "/images/padrao-covers/u_lion_winter.jpg",
  u_ls_cafe: "/images/padrao-covers/u_ls_cafe.jpg",
  u_ls_chibi: "/images/padrao-covers/u_ls_chibi.jpg",
  u_ls_mirror: "/images/padrao-covers/u_ls_mirror.jpg",
  u_ls_wellness: "/images/padrao-covers/u_ls_wellness.jpg",
  u_nw_arcane: "/images/padrao-covers/u_nw_arcane.jpg",
  u_nw_pulse: "/images/padrao-covers/u_nw_pulse.jpg",
  u_nw_warrior: "/images/padrao-covers/u_nw_warrior.jpg",
  u_phone_apple: "/images/padrao-covers/u_phone_apple.jpg",
  u_phone_neon: "/images/padrao-covers/u_phone_neon.jpg",
  u_phone_spotify: "/images/padrao-covers/u_phone_spotify.jpg",
  u_phone_street: "/images/padrao-covers/u_phone_street.jpg",
  u_rembrandt: "/images/padrao-covers/u_rembrandt.jpg",
  u_se_dark: "/images/padrao-covers/u_se_dark.jpg",
  u_se_eye: "/images/padrao-covers/u_se_eye.jpg",
  u_sf_cyber: "/images/padrao-covers/u_sf_cyber.jpg",
  u_sf_cybergoth: "/images/padrao-covers/u_sf_cybergoth.jpg",
  u_sk_cine: "/images/padrao-covers/u_sk_cine.jpg",
  u_sk_dark: "/images/padrao-covers/u_sk_dark.jpg",
  u_sk_dew: "/images/padrao-covers/u_sk_dew.jpg",
  u_sk_extreme: "/images/padrao-covers/u_sk_extreme.jpg",
  u_sk_raw: "/images/padrao-covers/u_sk_raw.jpg",
  u_vb_autumn: "/images/padrao-covers/u_vb_autumn.jpg",
  u_vb_film: "/images/padrao-covers/u_vb_film.jpg",
  u_vb_golden: "/images/padrao-covers/u_vb_golden.jpg",
  u_vb_rainy: "/images/padrao-covers/u_vb_rainy.jpg",
  men_ceo_boardroom: "/images/padrao-covers/men_ceo_boardroom.jpg",
  men_street_night: "/images/padrao-covers/men_street_night.jpg",
  men_athlete_gym: "/images/padrao-covers/men_athlete_gym.jpg",
  men_noir_detective: "/images/padrao-covers/men_noir_detective.jpg",
  men_tech_founder: "/images/padrao-covers/men_tech_founder.jpg",
  wom_runway_gold: "/images/padrao-covers/wom_runway_gold.jpg",
  wom_power_suit: "/images/padrao-covers/wom_power_suit.jpg",
  wom_golden_field: "/images/padrao-covers/wom_golden_field.jpg",
  wom_editorial_bw: "/images/padrao-covers/wom_editorial_bw.jpg",
  wom_rooftop_sunset: "/images/padrao-covers/wom_rooftop_sunset.jpg",
  u_magazine_cover: "/images/padrao-covers/u_magazine_cover.jpg",
  u_rain_moody: "/images/padrao-covers/u_rain_moody.jpg",
  u_golden_studio: "/images/padrao-covers/u_golden_studio.jpg",
  u_neon_street: "/images/padrao-covers/u_neon_street.jpg",
  u_cinematic_close: "/images/padrao-covers/u_cinematic_close.jpg",
};
