/**
 * Capas estáticas para a grelha Posters Pro.
 * Geradas por `scripts/generate-poster-covers.mjs`.
 */
export const POSTER_TEMPLATE_COVER_BY_ID = {
  music_street_energy: "/images/poster-covers/music_street_energy.jpg",
  music_night_vibes: "/images/poster-covers/music_night_vibes.jpg",
  music_chill_mode: "/images/poster-covers/music_chill_mode.jpg",
  music_stream_control: "/images/poster-covers/music_stream_control.jpg",
  music_street_chaos: "/images/poster-covers/music_street_chaos.jpg",
  music_night_frequency: "/images/poster-covers/music_night_frequency.jpg",
  music_night_frequency_2: "/images/poster-covers/music_night_frequency_2.jpg",
  music_classic_drop: "/images/poster-covers/music_classic_drop.jpg",
  music_gold_rush: "/images/poster-covers/music_gold_rush.jpg",
  music_new_single: "/images/poster-covers/music_new_single.jpg",
  music_vol_02: "/images/poster-covers/music_vol_02.jpg",
  music_club_night: "/images/poster-covers/music_club_night.jpg",
  music_underground_drop: "/images/poster-covers/music_underground_drop.jpg",
  music_sunset_sound: "/images/poster-covers/music_sunset_sound.jpg",
  music_new_release: "/images/poster-covers/music_new_release.jpg",
  food_restaurante_sabores_que_conectam: "/images/poster-covers/food_restaurante_sabores_que_conectam.jpg",
  food_sabor_qualidade: "/images/poster-covers/food_sabor_qualidade.jpg",
  food_burgers_artesanais: "/images/poster-covers/food_burgers_artesanais.jpg",
  food_oriental: "/images/poster-covers/food_oriental.jpg",
  food_experiencia_unica: "/images/poster-covers/food_experiencia_unica.jpg",
  fitness_beast_mode: "/images/poster-covers/fitness_beast_mode.jpg",
  fitness_train_hard: "/images/poster-covers/fitness_train_hard.jpg",
  fitness_strong_life: "/images/poster-covers/fitness_strong_life.jpg",
  fitness_iron_club: "/images/poster-covers/fitness_iron_club.jpg",
  fitness_discipline: "/images/poster-covers/fitness_discipline.jpg",
  fitness_fitness_zone: "/images/poster-covers/fitness_fitness_zone.jpg",
  motivational_discipline_today: "/images/poster-covers/motivational_discipline_today.jpg",
  motivational_no_limits: "/images/poster-covers/motivational_no_limits.jpg",
  motivational_no_limit: "/images/poster-covers/motivational_no_limit.jpg",
  motivational_new_chance: "/images/poster-covers/motivational_new_chance.jpg",
  motivational_mindset_power: "/images/poster-covers/motivational_mindset_power.jpg",
  motivational_execute: "/images/poster-covers/motivational_execute.jpg",
  flyers_lorem_ipsum_dolor: "/images/poster-covers/flyers_lorem_ipsum_dolor.jpg",
  flyers_lorem_ipsum: "/images/poster-covers/flyers_lorem_ipsum.jpg",
  flyers_lorem_ipsum_2: "/images/poster-covers/flyers_lorem_ipsum_2.jpg",
  flyers_lorem_ipsum_dolor_2: "/images/poster-covers/flyers_lorem_ipsum_dolor_2.jpg",
  flyers_lorem_ipsum_3: "/images/poster-covers/flyers_lorem_ipsum_3.jpg",
  flyers_lorem_ipsum_dolor_sit_amet: "/images/poster-covers/flyers_lorem_ipsum_dolor_sit_amet.jpg",
  flyers_raw_identity: "/images/poster-covers/flyers_raw_identity.jpg",
  flyers_modern_contrast: "/images/poster-covers/flyers_modern_contrast.jpg",
  flyers_dark_focus: "/images/poster-covers/flyers_dark_focus.jpg",
  flyers_street_impact: "/images/poster-covers/flyers_street_impact.jpg",
  flyers_editorial_frame: "/images/poster-covers/flyers_editorial_frame.jpg",
  flyers_modern_structure: "/images/poster-covers/flyers_modern_structure.jpg",
};
